### ISSUE TITLE
error with PG_EXPORTER_NAMESPACE="pg"

### ISSUE THREAD

**Issue by erifet** [Vonng/pg_exporter#15] opened 2021-05-28 09:06 UTC
Hi,

When in i put export PG_EXPORTER_NAMESPACE="pg" in default env file there is an error
..;pg_exporter[3999]: pg_exporter: error: strconv.ParseBool: parsing "pg": invalid syntax, try --help

If i exclude PG_EXPORTER_NAMESPACE but i set --namespace=pg in PG_EXPORTER_OPTS it work's
PG_EXPORTER_OPTS='--namespace=pg --log.level=info --log.format="logger:syslog?appname=pg_exporter&local=7"'

**Comment by Vonng** [comment] 2021-05-28 10:37
Thanks for the feedback.
It is caused by a stupid copy/paste typo.
And fixed by https://github.com/Vonng/pg_exporter/commit/f81e436413911b4a34207077c31198ba3d08e0a2

**Comment by Vonng** [comment] 2021-05-28 10:37
I've updated compiled binary in v0.4.0beta release.

**Closed by Vonng** 2021-05-28 10:37 UTC
